### PR TITLE
Initial implementation of driver enable.

### PR DESCRIPTION
**Pull request by justinlatimer**
I've implemented Driver Enable pins for the USART abstraction. Tested with RS485 hardware on an STM32G030. Happy for feedback. Thanks!

### CODE REVIEW

**Comment by andresv** [comment]
Could you run `cargo fmt`.

**Comment by justinlatimer** [comment]
Formatting updated!

**Comment by andresv** [comment]
Could you also add rs485 example.

**Comment by justinlatimer** [comment]
I've added an example of using the `usart_with_driver_enable()` function.

**Comment by andresv** [comment]
@dotcypress do you have any objections?

**Comment by dotcypress** [comment]
@justinlatimer  thank you for your help!

I'm not happy with `paste!` macro. Maybe we can implement this feature without macro hell.
I will take a deep look into it a bit later this week.

**Comment by justinlatimer** [comment]
Superseded by #109

**Pull request closed without merging**
