### PR TITLE
Update to stm32g0 0.15.1

### PR DESCRIPTION
**Pull request by stillinbeta**
status

| board     | status    |
|-----------|-----------|
| stm32g030 | :warning: |
| stm32g050 | :x:       |
| stm32g070 | :warning: |
| stm32g0b0 | :x:       |
| stm32g031 | :warning: |
| stm32g041 | :x:       |
| stm32g051 | :x:       |
| stm32g061 | :x:       |
| stm32g071 | :warning: |
| stm32g081 | :warning: |
| stm32g0b1 | :x:       |
| stm32g0c1 | :x:       |

### CODE REVIEW

**Comment by stillinbeta** [comment]
This is, best I can tell, the only way  to get support for g0b1 etc

**Comment by dotcypress** [comment]
CI is failed, could you take a look?

**Comment by stillinbeta** [comment]
This is a work in progress, I don't expect it to pass yet.

**Comment by dimpolo** [comment]
This seems to do the same as #79 and more. I'm happy to pass this over, just be aware that you'll likely be blocked on https://github.com/stm32-rs/stm32-rs/issues/641#issuecomment-1346940114

**Comment by andresv** [comment]
I am closing this one. 0.15.1 is added with: https://github.com/stm32-rs/stm32g0xx-hal/pull/149.
New targets should be added with separate PRs.

**Pull request closed without merging**
