### PR TITLE
new ADC with trigger from timer and use of 2xdma

### PR DESCRIPTION
**Pull request by oldsheep68**
Some extensions to ADC with:
- Two traits added (Injection Mode and DMA enable)

example that uses them:
- externel trigger of the ADC from TIM2
- DMA to transfer data from ADC to Memory
- DMA to transfer data from Memory-Buffer to UART
- UART in buffer mode
- oversampling is enabled by 16 and a bit shift is configured too

Tested with Nucleo32 STM32G031

The configuration of TIM2 is still included in the example, I was not able to change it only for the timers, which support that function

### CODE REVIEW

**Comment by andresv** [comment]
Thanks for the PR. Triggering ADC conversions with a timer is an excellent feature.
Did you also check other stm32 HAL crates for similar feature? It would be good if such features are somewhat similarly implemented in all HALs.

**Comment by oldsheep68** [comment]
Hi Andres

This is a good point. I didn't particularly check all stm32xx-hal variants before. I haven't seen any that I can remember. Typical extensions implemented are sequence mode or continuous mode, both is something different

Do you no of any, which has implemented this feature?

hal                                  ADC implementation with timer as trigger
stm32g4xx-hal             no
stm32f4xx-hal             no, but there is an example doing it very low level in the description
stm32f3xx-hal             no
stm32f3xx-hal-v2        no
stm32f1xx-hal             no
stm32f0xx-hal             no
stm32f7xx-hal             no hal craite found
stm32h7xx-hal           no, there is a command with lshift, since the device supports oversampling as well, this would need to be invested for this feature,  but i haven't found oversampling in the hal-api
stm32l0xx-hal            yes, it was not in my focus: stm32l0xx::adc::Trigger  is the definition, which selects an external adc trigger source as type
stm32l1xx-hal            no
stm32l4xx-hal            no adc support at all

For the stm32l0xx-hal, I didn't get the clue from the docs how this implementation works. May be with the examples I would get it... my Rust is really very basic, and to find out if it realy fills the gap.

Greetings,
Martin

________________________________

**Comment by andresv** [comment]
Formatting check fails at the moment. Could you fix that by running `cargo fmt`. Otherwise looks good to me.

**Comment by oldsheep68** [comment]
I think it should be ok from formatting point of view

**Pull request merged**
