### PR TITLE
rcc: uncomment SYSCFG support

### PR DESCRIPTION
**Pull request by agalakhov**

### CODE REVIEW

**Comment by andresv** [comment]
@burrbull has added this here: https://github.com/stm32-rs/stm32g0xx-hal/commit/f9b75f1e7415e116d6e0959beae49e5eddbe6fcf, so actually all good with this?

**Comment by agalakhov** [comment]
Ok I see, it is missing in some processor variants. Should be feature-gated for now.

**Review by dotcypress — CHANGES_REQUESTED** [review]
Let's remove TODO comment and we good to merge this one

**Review by dotcypress — APPROVED** [review]

**Comment by dotcypress** [comment]
Thank you @agalakhov !

**Pull request merged**
