### PR TITLE
Replace "stm32g07x" feature guards

### PR DESCRIPTION
**Pull request by ijager**
Replace with `stm32g070` or `stm32g071` or both. This is a first attempt to solve issue https://github.com/stm32-rs/stm32g0xx-hal/issues/18. 

Do you guys think it makes sense like this? 

WIP do not merge yet

### CODE REVIEW

**Comment by andresv** [comment]
Nice work!
Yes it makes sense. Are you also organizing needed PAC changes?

**Comment by ijager** [comment]
I am still hoping the correct SVD files show up somehow. If not I can give it a shot next week maybe, I have never worked with SVD files and that patch system yet.

**Comment by ijager** [comment]
I think this is good to go now. 

I also did a PR to crate a G070 and G071 PAC. I found some newer SVD files in STM32CubeIDE

**Comment by andresv** [comment]
Excellent!

Now we have to wait for this https://github.com/stm32-rs/stm32-rs/pull/395 to merge and after that at some point new `stm32g0` release will happen. Not sure actually how frequently PAC modifications are releases.

**Comment by ijager** [comment]
This PR does not depend yet on that future PAC release. It still uses the `stm32g0/stm32g07x` feature. But we can already use the new `stm32g070` `stm32g071` features for this crate.

```
# Cargo.toml
stm32g070 = ["stm32g0/stm32g07x", "stm32g0x0"]
stm32g071 = ["stm32g0/stm32g07x", "stm32g0x1"]
# deprecated, map to "stm32g071" for now
stm32g07x = ["stm32g0/stm32g07x", "stm32g071"]
```

Once we update to `stm32g0` **v0.12** or something we can change those lines to

```
# Cargo.toml
stm32g070 = ["stm32g0/stm32g070", "stm32g0x0"]
stm32g071 = ["stm32g0/stm32g071", "stm32g0x1"]
```

**Pull request merged**
